name: Test

on:
  pull_request:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: ./.github/actions/ruby-cache
    - run: bundle exec rubocop
      timeout-minutes: 10
