name: Sync

on:
  schedule:
    # Runs "At 00:00 on day-of-month 1"
    - cron: '0 0 1 * *'

  workflow_dispatch:

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  sync:
    name: Backend
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.CI_BOT_GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: ./.github/actions/ruby-cache
    - run: bundle exec ruby sync.rb
      timeout-minutes: 5
    - name: Commit and push
      run: |
        git config --global user.email "stream-bot@getstream.io"
        git config --global user.name "Stream Bot"
        branch="ci/sync-mock-server-$(date +%s)"
        git checkout -b "${branch}"
        git add src/jsons
        git commit -m "[CI] Sync Mock Server"
        git push --set-upstream origin "${branch}"
    - name: Trigger E2E tests on iOS and Android
      run: |
        gh workflow run e2e-test-cron.yml --repo GetStream/stream-chat-android
        gh workflow run cron-checks.yml --repo GetStream/stream-chat-swift
    - name: Create PR
      run: |
        body=$(cat <<'EOF'
        Automated mock server sync.

        Please verify the E2E test runs and move forward with the PR if they pass:
        - [ ] [Android](https://github.com/GetStream/stream-chat-android/actions/workflows/e2e-test-cron.yml?query=event%3Aworkflow_dispatch)
        - [ ] [iOS](https://github.com/GetStream/stream-chat-swift/actions/workflows/cron-checks.yml?query=event%3Aworkflow_dispatch)
        EOF
        )
        gh pr create --base main --title "[CI] Sync Mock Server" --body "$body"
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: "You shall not pass!"
        job_name: "${{ github.workflow }}: ${{ github.job }}"
        fields: message,commit,author,action,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      if: failure()
